In [5]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split
print('a')

a


In [14]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

array3 = np.array([[1,2,3]])
print('array3 shape: ', array3.shape)

print('array1: {:0}차원, array3: {:1}차원'.format(array1.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array3 shape:  (1, 3)
array1: 1차원, array3: 2차원


In [4]:
import numpy as np

array_int=np.array([1,2,3])
print(array_int,array_int.dtype)
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

[1 2 3] int32
[1. 2. 3.] float64


In [7]:
import numpy as np
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

array_float=array1.astype('float64')
print(array_float, array_float.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
[1. 2. 3.] float64


In [18]:
import numpy
sequence_array=np.arange(10)
print(sequence_array)

zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype)

array1=np.arange(8)
print(array1)

array2=array1.reshape(2,4)
print(array2)

array3=array1.reshape(4,-1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [23]:
array1d=np.arange(start=1,stop=10)
print(array1d)

array2d= array1d.reshape(3,3)
print(array2d)

array3=array2d[[0,1],2]
print(array3.tolist())

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
